version: "3.9"
volumes:
  data:
networks:
  dbase:
  web:
services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - data:/var/lib/postgresql/data
      - ./scripts:/scripts
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - dbase
  frontend:
    image: nginx:1.23
    volumes:
      - ./web/build/web:/usr/share/nginx/html/
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    networks:
      - web
    depends_on:
      - app
  app:
    image: dart:2.19
    volumes:
      - ./app:/app
    working_dir: /app/bin
    command: bash ./app.sh
    networks:
      - dbase
      - web
    depends_on:
      - db